name: Build and Publish Docker Image

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: client-image:${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build -t $IMAGE_NAME -f Dockerfile .
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u gardusig --password-stdin
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/gardusig/$IMAGE_NAME
